site_name: "gms-nallo-methylation-dashboard"
site_author: "Jyotirmoy Das"
site_description: "A comprehensive documentation for GMS-nallo-methylation-dashboard."

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - search.suggest
    - search.highlight
    # - toc.integrate
    - content.action.edit
    - content.code.copy
    - versioning
    - icons

plugins:
  - search
  - mike

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.details  
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.blocks.html
  - pymdownx.arithmatex:
      generic: true
  - codehilite
  - toc:
      permalink: true     
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md


extra:
  version:
    provider: mike
  current_year: !!python/object/apply:str ["2026"]

extra_css:
  - styles/extra.css

extra_javascript:
  - https://fonts.googleapis.com/css2?family=Fira+Code&family=Inter:wght@400;600&display=swap
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-MML-AM_CHTML
  - js/github-stats.js